spring:
  redis:
    host: ${redis.host:localhost}
    port: ${redis.port:6379}
    password: ${redis.password}

stomp-redis-relay:
  channel-prefix: '/channel/'

logging.level.me.itzg.stomprelay: TRACE

